version: "3.9"
services:
  db:
    image: docker-public.docker.devstack.vwgroup.com/postgres
    container_name: cocktail-machine-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db1

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocktail-machine-server
    restart: always
    ports:
      - "5000:80"
    environment:
      BASIC_AUTH_FORCE: "False"
      DATABASE_URL: "postgresql://admin:123456@db/db1"
      RECREATE_DATABASE: "True"
      DUMMY_DATABASE: "True"
      CORS: "*"
    depends_on:
      - db

  nginx:
    image: docker-public.docker.devstack.vwgroup.com/nginx
    container_name: cocktail-machine-front-end
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/www/data:ro
    depends_on:
      - server