version: "3.9"
services:
  db:
    image: postgres
    container_name: cocktail-machine-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db1

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cocktail-machine-server
    container_name: cocktail-machine-server
    restart: always
    ports:
      - "5000:80"
    environment:
      BASIC_AUTH_FORCE: "False"
      DATABASE_URL: "postgresql://admin:123456@db/db1"
      RECREATE_DATABASE: "True"
      DUMMY_DATABASE: "True"
      CORS: "*"
    depends_on:
      - db

  pages:
    image: cocktail-machine-pages
    container_name: cocktail-machine-pages
    restart: always
    entrypoint: gunicorn -b=:5000 --workers=2 'cocktail_machine:create_app()'
    ports:
      - "80:80"
    depends_on:
      - server